### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by bitcoinbrisbane** [Azure/azure-content#2225] opened 2014-11-07 05:26 UTC
The deploy from git links are broken.

**Comment by deneha** [comment] 2015-05-01 21:30
@bitcoinbrisbane Hi there!  Sorry for the delay.  Is there still a problem?  If so, could you please provide a page and point to where the problem is located?  Thank you!

**Comment by deneha** [comment] 2015-05-06 22:08
@bitcoinbrisbane I'm closing this issue.  Please let us know if the problem persists.

**Closed by deneha** 2015-05-06 22:08 UTC
