### ISSUE TITLE
link to download "Python Tools 2.1 for Visual Studio " is broken

### ISSUE THREAD

**Issue by h4nN** [Azure/azure-content#3633] opened 2015-05-22 23:57 UTC
Link to download "Python Tools 2.1 for Visual Studio " is broken

**Comment by jimbe** [comment] 2015-05-26 16:18
Nicchub, what is the URL of the page with the broken link?

**Comment by deneha** [comment] 2015-07-27 17:51
@nicchub Is this issue still a problem for you?  Please let us the know the URL to the page where the issue is present.  We'll keep this issue open a few more days to see if the issue is still a problem before we close.

**Comment by tysonn** [comment] 2015-07-27 18:09
@huguesv - Hugues, can you look into this? It's most likely in your articles based on a search of the repo.

**Comment by huguesv** [comment] 2015-07-27 23:07
it's in this page, the link from the requirements section is broken.
https://azure.microsoft.com/en-us/documentation/articles/web-sites-python-create-deploy-django-app/

**Comment by deneha** [comment] 2015-08-10 16:11
@h4nN The issue has been corrected.  You should see the update by Noon PST today in the live documentation.  Please let us know if we can assist you further.  I'm closing this issue now.

**Closed by deneha** 2015-08-10 16:11 UTC
Labels: question
